<?php $this->headLink()->appendStylesheet('/css/overtime.css'); ?>

<div class="row">
    <div class="col-sm-12">
        <div class="text-center">
            <h1>OVERTIME ADMIN</h1>
            <a class="btn btn-default btn-xs" href="<?php echo $this->url('zfcadmin/overtime/add'); ?>">
                <span class="glyphicon glyphicon-plus"></span>
            </a>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-sm-offset-3 col-sm-6">
        <div class="text-center">
            <div id="filter-nav">
                <div class="btn-group">
                    <div class="btn-group">
                        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                            View <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu">
                            <li><a href="<?php echo $this->url('zfcadmin/overtime/list', ['to' => null, 'from' => null, 'all' => null], true); ?>">Month</a></li>
                            <li><a href="<?php echo $this->url('zfcadmin/overtime/list', ['to' => null, 'from' => null, 'all' => 1], true); ?>">All</a></li>
                        </ul>
                    </div>

                    <?php if(!$this->paramEnabled('all')): ?>
                        <a class="btn btn-default" href="<?php echo $this->monthPagination('zfcadmin/overtime/list')->prevMonth(); ?>">Prev Month</a>
                        <a class="btn btn-default" href="<?php echo $this->monthPagination('zfcadmin/overtime/list')->nextMonth(); ?>">Next Month</a>
                    <?php endif; ?>

                    <div class="btn-group">
                        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                            State <span class="caret"></span>
                        </button>
                        <?php echo $this->overtimeStates('zfcadmin/overtime/list')->setUlFormat('<ul class="dropdown-menu">%s</ul>')->render(); ?>
                    </div>

                    <div class="btn-group">
                        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                            User <span class="caret"></span>
                        </button>
                        <?php echo $this->users('zfcadmin/overtime/list')->setUlFormat('<ul class="dropdown-menu">%s</ul>')->render(); ?>
                    </div>
                </div>

                <div id="filter-params">
                    <?php echo $this->currentFilterParams('zfcadmin/overtime/list'); ?>
                </div>
            </div>
        </div>

        <?php if (count($this->overtime)): ?>
            <table class="table">
                <thead>
                <tr>
                    <th>User</th>
                    <th>Date</th>
                    <th>Duration (Hours)</th>
                    <th>Notes</th>
                    <th>State</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                <?php foreach($this->overtime as $overtime): ?>
                    <tr>
                        <td><?php echo $overtime->getUser()->getDisplayName(); ?></td>
                        <td><?php echo $overtime->getDate()->format('d-m-Y'); ?></td>
                        <td><?php echo $overtime->getDuration(); ?></td>
                        <td><?php echo $this->escapeHtml($overtime->getNotes()); ?></td>
                        <td><span class="label label-<?php echo $this->escapeHtml($overtime->getState()->getState()); ?>"><?php echo $this->escapeHtml($overtime->getState()->getState()); ?></span></td>
                        <td>
                            <div class="btn-group">
                                <a class="btn btn-default btn-xs" href="<?php echo $this->url('zfcadmin/overtime/edit', ['id' => $overtime->getId()]);?>"><span class="glyphicon glyphicon-pencil"></span></a>
                                <a class="btn btn-default btn-xs" href="<?php echo $this->url('zfcadmin/overtime/delete', ['id' => $overtime->getId()]);?>"><span class="glyphicon glyphicon-trash"></span></a>
                            </div>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>

            <?php
            // add at the end of the file after the table
            echo $this->paginationControl(
            // the paginator object
                $this->overtime,
                // the scrolling style
                'sliding',
                // the partial to use to render the control
                ['partial/paginator.phtml', 'JhHub'],
                // the route to link to when a user clicks a control link
                [
                    'route' => 'zfcadmin/overtime/list',
                ]
            ); ?>

            <div class="text-center">
                <span class="badge"><?php echo $this->overtime->getTotalItemCount(); ?></span>
            </div>
        <?php else: ?>
            <div class="alert alert-info">No Overtime Found!</div>
        <?php endif; ?>

    </div>
</div>
